version: 3

tasks:
  update:
    desc: Install dependencies
    cmds:
      - helm dependency update ./infra/chart
  build:
    desc: Build dependencies
    cmds:
      - helm dependency build ./infra/chart
  remove:
    desc: Removes the chart
    cmds:
      - helm uninstall {{.RELEASE}}
  install:
    desc: Installs the chart
    deps:
      - dep
    cmds:
      - >-
        helm upgrade --install  {{.RELEASE}} ./infra/chart
        --values ./infra/chart/values.yaml
        --values ./infra/chart/values{{.LANDSCAPE}}.yaml
  template:
    desc: Templates the chart
    deps:
      - update
    cmds:
      - >-
        helm template {{.RELEASE}} ./infra/chart
        --values ./infra/chart/values.yaml
        --values ./infra/chart/values{{.LANDSCAPE}}.yaml
  debug:
    desc: Debugs the chart
    deps:
      - update
    cmds:
      - >-
        helm template --debug {{.RELEASE}} ./infra/chart
        --values ./infra/chart/values.yaml
        --values ./infra/chart/values{{.LANDSCAPE}}.yaml
